basePath: /
definitions:
  controllers.login:
    properties:
      email:
        example: youremail@163.com 正确的邮箱格式
        format: string
        type: string
      mobile:
        example: 手机号码
        format: string
        type: string
      password:
        example: 用户密码
        format: string
        type: string
      username:
        example: 用户名，英文数字组成
        format: string
        type: string
    required:
    - mobile
    - password
    type: object
  controllers.register:
    properties:
      confirmPassword:
        example: 确认密码
        format: string
        type: string
      email:
        example: youremail@163.com 正确的邮箱格式
        format: string
        type: string
      mobile:
        example: 手机号码
        format: string
        type: string
      password:
        example: 设置密码
        format: string
        type: string
      username:
        example: 用户名，英文数字组成
        format: string
        type: string
    required:
    - confirmPassword
    - mobile
    - password
    type: object
host: 9200.gpu.raidcdn.cn:9700
info:
  contact:
    email: ggxxde@163.com
    name: API Support
    url: http://9200.gpu.raidcdn.cn:9700
  description: 这是API说明文档，开发服务器才有， 正式部署之后没有。  认证时候填 token eyJhbGciOiJIU...(注意token后面有个空格，
    token向管理员申请)
  license:
    name: Apache 2.0
    url: http://9200.gpu.raidcdn.cn:9700
  termsOfService: http://9200.gpu.raidcdn.cn:9700
  title: API说明
  version: "1.0"
paths:
  /api1/authping:
    get:
      consumes:
      - application/json
      description: ping检查网络是否正常，需要登录
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 连通性（需要认证）
  /api1/batchinfo:
    get:
      consumes:
      - application/json
      description: 获得所有批次信息
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 数据/项目（需要认证）
  /api1/categoryinfo:
    get:
      consumes:
      - application/json
      description: 获得细胞分类信息
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 数据/项目（需要认证）
  /api1/createdataset:
    post:
      consumes:
      - application/json
      description: 新建数据/项目
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 数据/项目（需要认证）
  /api1/dtinfo:
    get:
      consumes:
      - application/json
      description: 获得所有图片及标注的统计信息
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 数据/项目（需要认证）
  /api1/getimgnptypebymids:
    post:
      consumes:
      - application/json
      description: 通过所选中的批次/病例/图片, 返回N/P图片的个数统计
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 数据/项目（需要认证）
  /api1/imglistsofwanted:
    get:
      consumes:
      - application/json
      description: 获得所选批/次病/细胞类型的图片
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 数据/项目（需要认证）
  /api1/imglistsonebyone:
    get:
      consumes:
      - application/json
      description: 通过图片的ID获得对应的所有标注信息
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 数据/项目（需要认证）
  /api1/job:
    post:
      consumes:
      - application/json
      description: python端请求一个任务（数据处理/训练/预测），python端会指定请求任务的状态和类型
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
        "401":
          description: '{"data": "cookie token is empty", "status": 63}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 任务（需要认证）
  /api1/joblog:
    get:
      consumes:
      - application/json
      description: 获得任务数据处理/训练/预测后端产生的log
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 任务（需要认证）
  /api1/jobmodel:
    get:
      consumes:
      - application/json
      description: 获得训练任务生成模型的信息
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 模型（需要认证）
  /api1/jobpercent:
    get:
      consumes:
      - application/json
      description: 获得任务进度（数据处理/训练/预测）
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 任务（需要认证）
  /api1/jobresult:
    get:
      consumes:
      - application/json
      description: 获得任务状态（数据处理/训练/预测）
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 任务（需要认证）
    post:
      consumes:
      - application/json
      description: python端更新任务状态/进度（数据处理/训练/预测）
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 任务（需要认证）
  /api1/listdatasets:
    post:
      consumes:
      - application/json
      description: 按数据库存储顺序依次获得数据/项目信息
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 数据/项目（需要认证）
  /api1/medicalidinfo:
    get:
      consumes:
      - application/json
      description: 获得所有病例信息
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 数据/项目（需要认证）
  /api1/ping:
    get:
      consumes:
      - application/json
      description: ping检查网络是否正常
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      tags:
      - API1 连通性（不需要认证）
  /api1/savemodel:
    get:
      consumes:
      - application/json
      description: 把训练任务生成模型信息存数据库
      produces:
      - application/json
      responses:
        "200":
          description: "{\"ping\": \"pong\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - API1 模型（需要认证）
  /api1/userinfo:
    get:
      consumes:
      - application/json
      description: 获得当前用户信息
      produces:
      - application/json
      responses:
        "200":
          description: "{\"data\": \"ok\",\t\"status\": 200}"
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 用户信息
      tags:
      - API1 用户
  /user/login:
    post:
      consumes:
      - multipart/form-data
      description: 用户通过邮箱/用户名/手机号登录
      parameters:
      - description: 登录信息表单
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/controllers.login'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 'expire": "当前token到期时间", "status": 200, "token": "token的字符串","user":
            {"id": 3,"mobile": "string","email": "string","name": "string","image":
            "http://workaiossqn.tiegushi.com/xdedu/images/touxiang.jpg","type_id":
            1000,"created_at": "2019-09-12T10:05:39Z","updated_at": "2019-09-12T03:34:17Z"}}'
          schema:
            type: string
      summary: 登录
      tags:
      - API1 用户
  /user/logout:
    post:
      consumes:
      - application/json
      description: 已经登录用户注销
      produces:
      - application/json
      responses:
        "200":
          description: 'status": 200, "data": "ok"}'
          schema:
            type: string
      summary: 已经登录用户注销
      tags:
      - API1 用户
  /user/register:
    post:
      consumes:
      - multipart/form-data
      description: 注册新用户
      parameters:
      - description: 注册信息表单
        in: body
        name: Register
        required: true
        schema:
          $ref: '#/definitions/controllers.register'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: "{\"data\": \"User already exist\",\t\"status\": 70}"
          schema:
            type: string
      summary: 注册
      tags:
      - API1 用户
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
